version: "3.9"

services:
  proxy:
    build:
      context: ..
    ports:
      - "8080:8080"
    volumes:
      - ./config_example.yaml:/config/config_example.yaml:ro
      - ./cert.crt:/etc/ssl/certs/cert.crt:ro
      - ./private.key:/etc/ssl/private/private.key:ro
      - ./rsa_private_key.pem:/etc/app/private/rsa_private_key.pem:ro
    command:
      - --config
      - /config/config_example.yaml
      - --set
      - log.format=text
