builds:
  -
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - darwin
      - linux
      - windows

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386, amd64 and arm64.
    goarch:
      - amd64
      - arm64

changelog:
  skip: false
  use: git
  sort: asc

  groups:
    - title: Breaking Changes
      regexp: "^.*BREAKING CHANGE[(\\w)]*:+.*$"
      order: 0
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 1
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 2
    - title: 'Enhancements'
      regexp: "^.*(chore|build|style|refactor|perf|test)[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 999

  filters:
    exclude:
      - '^docs'
      - '^ci'
      - typo

archives:
  # Additional files/template/globs you want to add to the archive.
  - files:
      - LICENSE
      - README.md
      - example/cert.crt
      - example/config_example.yaml
      - example/docker-compose.yaml
      - example/private.key
      - example/rsa_private_key.pem
      - example/rsa_public_key.pub
